emscripten-core/emscripten-fastcomp

lib/Transforms/NaCl/FlattenGlobals.cpp

Work around Visual Studio bug https://connect.microsoft.com/VisualStudio/feedback/details/1085387 .

VS2013 fix for getRelocData.

---

lib/Target/JSBackend/JSBackend.cpp

Flagging this correctly results in some errors not being generated
when compiling.

JSWriter::error() will not return.

---

lib/Target/JSBackend/JSBackend.cpp

Only emit stack restoration when the stack has been bumped by the
current function. This means that all functions must exercise
proper stack discipline.
This is done by looking for any static allocas during the computation
of the frame offset as well as any dynamic allocas when emitting the
code for the function.
This addresses https://github.com/kripken/emscripten/issues/3071.
cc: @chadaustin

Optimize stack restoration.

---

lib/Support/Triple.cpp

My merge into the PNaCl repo moved some of the Triple.cpp changes to be more consistent, which avoided merge conflicts and causes needless redundancy.

Clean redundant code in Triple

---

lib/Transforms/NaCl/ExpandInsertExtractElement.cpp

CopyDebug is accessible now that ExpandInsertExtractElement includes NaCl.h. I'd rather use IRBuilder in general and remove CopyDebug in the future, but it'll ahve to do for now. Also merge in the change for the create* function.

Remove build warning in ExpandInsertExtractElement

---

lib/Transforms/NaCl/PromoteIntegers.cpp

No need to forward declare ConversionState anymore.
No need for getAnalysisUsage on DataLayoutPass anymore: LLVM's handling of DataLayoutPass changed in teh last few months and runOnFunction now simply creates the DataLayout from the Module.

Fully merge PromoteIntegers

---

tools/opt/opt.cpp

I grouped Emscripten pass initialization lower, so the changes didn't merge conflict. I'll fix the double initialization of NoExitRuntime below in the PNaCl repo to reduce merging.

Clean up double initialization in opt.

---

lib/IR/Module.cpp

This was added by @juj in e8fdaf5a2f09e335bdc5a6689b298e54337cc737 to fix the VS2010 build. It's either not needed anymore because the diff from LLVM upstream on this file is empty, or it's instead needed in upstream LLVM (I doubt it, since LLVM does build correcting on MSVC).

Remove raw_ostream localmod

---

configure

This just makes our diff smaller.

Add back a space that was removed in emscripten, is in LLVM.

---

CMakeLists.txt

This is closer to LLVM's CMakeLists.txt, and has the localmod marker.

Clean up CMakeLists.txt merge.

---

lib/Target/JSBackend/Relooper.cpp

Variadic macros need at lest one variadic argument (## is a GCC extension).
Some unused local variables.
Casting away const-ness (need const_cast then static_cast).
No need to do 'if (X) free(X);' since free(0) is valid.
Simplify away some (void*) voodoo.

Fix Relooper.cpp build warnings.

---

lib/Transforms/NaCl/ExpandVarArgs.cpp

kripken added this in 6198caf1 but it's not needed anymore (and was incorrect): the code was putting varargs on the stack as a packed struct which caused misaligned reads and writes, I fixed the issue by making the struct non-packed and using the target's prefered alignment for each element instead. The alloca should be aligned to the target's preference too, so everything should now be neatly aligned. This pass runs pre-opt, so the optimizer can figure out the alignment of all the loads and stores and foster further harmony in the memory.

Remove extra vararg store alignment.

---

lib/Transforms/NaCl/ExpandVarArgs.cpp

@sunfishcode added this change in 338da97e before ExpandVarArgs used IRBuilder. Now that it uses IRBuilder the change isn't needed because it'll automatically create constexprs when it can.

Remove ExpandVarArgs localmod.

---

lib/Target/JSBackend/JSBackend.cpp

This PR is a bug fix for issue https://github.com/kripken/emscripten/issues/3401.

Emit debug info only when the line number is greater than 0.

---

lib/Target/JSBackend/JSBackend.cpp
test/CodeGen/JS/getelementptr.ll

This is the first part of the fix for [the recent Poppler regression on Odin](https://bugzilla.mozilla.org/show_bug.cgi?id=1159404).

When the base of a getelementptr is a GlobalVariable, fold its address into the constant offset.

---

lib/Target/JSBackend/JSBackend.cpp
lib/Target/JSBackend/Relooper.h

The goal is to make it so that compiling with identical sources produces identical output js files each time you compile.  The strategy is to use an "ordered" version of std::map and std::set whose syntax is the same as map and set, but whose begin() -> end() iterate elements in the order they were added to the container (unlike map and set which iterate according to the comparison operator of T).  Compile times with these modifications are nearly identical to the existing version on the projects I tried it on.

making js output consistent each time it compiles the same sources

---

lib/Target/JSBackend/Relooper.cpp

fixes broken build due to missing ministring.h

Replace ministring with std::string in emcc build of Relooper.cpp

---

lib/Transforms/NaCl/PromoteIntegers.cpp

Emscripten: Fix use of an uninitialized boolean variable in lib/Transforms/NaCl/PromoteIntegers.cpp. Windows debug builds crash in this function a few lines down when runtime checks catch a load of `Modified`, and dump with a trace like
0x00007FF7C2F3688D (0xCCCCCCCCCCCCCCCC 0xCCCCCCCCCCCCCCCC 0xCCCCCCCCCCCCCCCC 0xCCCCCCCCCCCCCCCC), failwithmessage() + 0x22D bytes(s), f:\dd\vctools\crt\crtw32\rtc\error.cpp, line 222
0x00007FF7C2F369BF (0x00000098C33AE720 0x00007FF7C2F35D40 0xCCCCCCCC00000000 0xCCCCCCCCCCCCCCCC), _RTC_UninitUse() + 0xFF bytes(s), f:\dd\vctools\crt\crtw32\rtc\error.cpp, line 475
0x00007FF7C240EB79 (0x00000098C35963E0 0x00000098C33AE8E0 0x00000098C5BD4E30 0x00000098C35D9C20), processFunction() + 0x229 bytes(s), c:\code\emsdk\clang\fastcomp\src\lib\transforms\nacl\promoteinteg …

fix_uninit_bool_use

---

lib/Target/JSBackend/CallHandlers.h

Fixes codegen so that Float64x2 code works equally in node.js and SpiderMonkey.

Float64x2 working in simd polyfill

---

lib/Target/JSBackend/JSBackend.cpp

This fixes emscripten issue 3787. The problem began in 338da97ed47659b9ef04f60067f84cafc93e3dd3.
I assume this is the right fix, but since we have other SIMD breakage, I'm not sure I can trust the test suite, so not pushing this directly.

fix an unnecessary ad-hoc assign, which can mark a param as a UsedVar

---

lib/Target/JSBackend/JSBackend.cpp
test/CodeGen/JS/simd-fcmp.ll
test/CodeGen/JS/simd-loadstore.ll
test/CodeGen/JS/simd-shuffle.ll

When encountering float literals that have noncanonical NaN bit patterns in a SIMD vector, don't attempt to create a float SIMD vector directly out of them, since JS source can't represent NaNs with noncanonical bits. Instead, create an int SIMD vector and cast it to float one to detour to the SIMD vector with correct bits intact. Fixes https://github.com/kripken/emscripten/issues/2840,  https://github.com/kripken/emscripten/issues/3560, https://github.com/kripken/emscripten/issues/3010 and https://github.com/kripken/emscripten/issues/3403.

Fix NaNs in SIMD

---

lib/Target/JSBackend/JSBackend.cpp

PR for kripken/emscripten#3804.
Make a set of different arities in template expansions of each `EM_ASM` block.
They need to be ordered to take a shortcut in `emscripten.py` so there's a new typedef `OrderedIntSet` in case `IntSet` is later changed to `std::unordered_set`.

Allow multiple arities per EM_ASM block, fixes kripken/emscripten#3804.

---

lib/Target/JSBackend/JSTargetTransformInfo.cpp
lib/Target/JSBackend/JSTargetTransformInfo.h

This adds some `TargetTransformInfo` logic to deny some bad SIMD types, seen when autovectorizing Bullet.
Btw, one of the things it tries is to vectorize things like `<4 x btVector3*>`, which I suppose we could support in theory, as it's just a 32-bit int.

Say that bad SIMD types are completely unacceptable

---

lib/Transforms/NaCl/FlattenGlobals.cpp

This field was only used in an assert message, so just calculate it
at that point.

FlattenGlobals: Remove unused BufEnd field.

---

lib/Target/JSBackend/JSBackend.cpp

Add support for SIMD.js boolean types to fix asm.js validation on up-to-date spec implementation on FF Nightly.
This addresses https://github.com/kripken/emscripten/issues/3980.

simd_js_spec_update

---

lib/Target/JSBackend/NaCl/ExpandI64.cpp

This is for https://github.com/kripken/emscripten/issues/4025. It does two things:
1. It removes "fetch_and_" from the names, based on what you (@juj) said in that bug. But I'm confused. Is this correct?
2. It defines the methods if they are not already linked in, which was a bug.

Create atomic functions in ExpandI64 if necessary

---

lib/Target/JSBackend/CallHandlers.h
lib/Target/JSBackend/JSBackend.cpp

Add casts to return values of atomic operations. Even though not strictly needed, these help implement -s USE_PTHREADS=2 build mode for backwards compatibility with non-pthreads-capable browsers.

use_pthreads_2_fallback

---

lib/Target/JSBackend/CallHandlers.h
lib/Target/JSBackend/JSBackend.cpp

This avoids unnecessary missing function stubs like you noticed in https://github.com/kripken/emscripten/issues/4068#issuecomment-179486581
See comment in the commit for more details.
It does come with the risk that if we forget to do a declare in a call handler, it can fail. But I think it's still worth it to avoid unnecessary code. Thoughts?

Avoid auto-declaring in call handlers

---

lib/Target/JSBackend/CallHandlers.h
lib/Target/JSBackend/JSBackend.cpp

More information is available here: https://gist.github.com/hackcasual/ea77cc31c6dafdda7274
This adds a pass entirely behind a flag to collect the LLVM DI entities for the program, then emits a JSON type tree from those
The debug intrinsics are designed to compile down to no-ops (however I believe they make the generated output non asm.js compatible). They are designed to be replaced by a debugger for reporting on live variables

Added DWARF style debugging information extraction.

---

lib/Target/JSBackend/NaCl/ExpandStructRegs.cpp

As you requested on kripken/emscripten#4031, here is my fix for recursively referenced insertvalue instructions. The fix removes cleaning up insertvalue instructions, which is not ideal. How can the clean up of these instructions be done recursively?

Fix for recursively referenced insertvalue

---

lib/Target/JSBackend/CallHandlers.h

This adds support for the llvm.sin.f(32|64) intrinsic to fastcomp. More details can be found in the issue kripken/emscripten#4338. The accompanying change to Emscripten is in pull request kripken/emscripten#4353

Add support for llvm.sin.f(32|64) intrinsics

---

lib/Target/JSBackend/NaCl/NormalizeAlignment.cpp
lib/Target/JSBackend/NaCl/SimplifyStructRegSignatures.cpp

Visual Studio 2015 Update 3 (latest version) gets confused by
for (A B : C)
if (x)
else if (y)
and it complains that the `else` statement doesn't have a matching `if`. This has something to do with the modern style of `for` statement, at least in old style `for`s, the issue doesn't occur. Adding explicit block works around the problem.

Fix Visual Studio 2015 build.

---

lib/Target/JSBackend/CallHandlers.h
lib/Target/JSBackend/ExpandBigSwitches.cpp
lib/Target/JSBackend/JSBackend.cpp

This adds support for emitting i64 operations and values directly from the fastcomp backend. This is now possible since the binaryen wasm optimizer has made running the asm.js optimizer no longer necessary. Since we can now go straight from the backend into binaryen, we can keep i64s as i64s (by not running the ExpandI64 pass, and emitting a bunch of new `i64_*` intrinsics). The code is no longer valid asm.js, but that doesn't matter.
Of course we can only do this when we are in "wasm-only" mode, since sometimes we do expect to either run the asm.js, or we are actually running the asm.js optimizer (if either the user requested it explicitly, or an option the user requested mandates it). So this is behind a flag. But by default we should be able to pass that flag.
This started as an …

wasm i64 support

---

lib/Target/JSBackend/CallHandlers.h
lib/Target/JSBackend/JSBackend.cpp

When in wasm-only mode, emit special intrinsics for loads, stores and bitcasts, to avoid asm.js limitations.

More wasm-only opts

---

lib/Target/JSBackend/CallHandlers.h

It looked like an ffi and since asm.js ffis don't have real f32 support, it ended up cast to f64 and back.
This marks it as not an ffi.

Fix f32_copysign

---

lib/Target/JSBackend/CallHandlers.h

Necessary for https://github.com/kripken/emscripten/pull/4698 and https://github.com/kripken/emscripten/pull/4699

Support llvm_(ceil|floor)_f32, llvm_cos_f(32|f64)

---

lib/Target/JSBackend/NaCl/ExpandI64.cpp

Show an error on i64 inputs to EM_ASM

---

lib/Target/JSBackend/CallHandlers.h
lib/Target/JSBackend/JSBackend.cpp

This together with a binaryen and emscripten PR implement dynamic linking in wasm. This is done according to the recently-merged
https://github.com/WebAssembly/tool-conventions/blob/master/DynamicLinking.md
and in particular the dynamic library is a wasm module.
This fastcomp PR adds some fixes for using wasm tables more extensively, which is necessary for dynamic linking.

Binaryen dynamic linking

---

lib/Target/JSBackend/JSBackend.cpp

As due to asm.js overloading of float/double, we can't legalize them later - we don't know the type of the indirect calls.
Noted in https://bugzilla.mozilla.org/show_bug.cgi?id=1334239#c14

create a legalizer stub for imported methods with float32 params/return values that go in tables

---

lib/Target/JSBackend/LLVMBuild.txt

Without this, I get a bunch of 'undefined references' when linking.
This will merge into #166

Add missing library dependencies

---

lib/Target/JSBackend/CallHandlers.h
lib/Target/JSBackend/JSBackend.cpp

`std::to_string` is not available on freebsd 10, so use streams instead.
cc rust-lang/rust#40123

Use streams instead of std::to_string

---

lib/Target/JSBackend/NaCl/ExpandStructRegs.cpp

Fixes #176.
When something like `struct Foo { int bar[10]; }` was expanded, this would generate `getelementptr` to the array `bar` and then a `load` from that pointer. The code failed to recognise that a `load` of an array needed to be further expanded, causing the assertion later.

Require re-running expansion after expanding to an array

---

lib/Target/JSBackend/NaCl/ExpandStructRegs.cpp

More array splitting, handle select and phi

---

lib/Target/JSBackend/CallHandlers.h
lib/Target/JSBackend/JSBackend.cpp

For JS/Web platform, calls to JS imports are wrapped to convert i64 to
i32 and f32 to f64. Likewise calls from JS into exports do the inverse
wrapping. However, for non-web embeddings this is probably undesirable.
This change provides an option to disable that wrapping and
use the original types for the call. This is used by emscripten with the JS_FFI option (https://github.com/kripken/emscripten/pull/5168). A related option is also proposed for binaryen (https://github.com/WebAssembly/binaryen/pull/984).

emscripten-js-ffi opt to disable JS FFI mangling.

---

lib/Target/JSBackend/JSBackend.cpp

Remove software implemented emscripten_atomic_exchange_u32() polyfill, which is not needed anymore since Atomics.exchange() is part of the spec and implemented in shipping browsers. https://github.com/kripken/emscripten/issues/3498
Merge with https://github.com/kripken/emscripten/pull/5438

remove_atomics_exchange_polyfill

---

include/llvm/ADT/DenseSet.h

Cherry-picking https://github.com/llvm-mirror/llvm/commit/fe78796b302967097ce983205c2f8450107cf948, fixes #185.
This will help VS2017 users before #191 lands.

Fix VS2017 build error (cherry-picking from LLVM repo)

---

lib/Target/JSBackend/JSBackend.cpp

Don't lower away atomics when building for wasm

---

lib/Target/JSBackend/JSBackend.cpp

Atomics can then still be used in single-threaded codegen

Make lowerAtomic pass conditional on disabling pthreads

---

lib/Target/JSBackend/CallHandlers.h
lib/Target/JSBackend/JSBackend.cpp
lib/Target/JSBackend/NaCl/ExpandVarArgs.cpp

This expands `EM_ASM` handling to allow specifying how the JS code is run in multithreaded environment: a) locally (synchronously) on the calling thread, b) synchronously proxied to main browser thread, or c) asynchronously proxied to main browser thread.
This needs a matching Emscripten side PR to land, I'll get to that at some point.

Em asm calltype

---

lib/Target/JSBackend/CallHandlers.h

The corresponding change to Emscripten is this PR:
https://github.com/kripken/emscripten/pull/5978, and relates to this
issue: https://github.com/kripken/emscripten/issues/5976. I’m using
https://github.com/kripken/emscripten-fastcomp/pull/143 as a model.

Add llvm.minnum.f(32|64) and llvm.maxnum.f(32|64) intrinsics

---

lib/Target/JSBackend/JSBackend.cpp

According to kripken/emscripten#6068, it is not necessary anymore.

Remove 2-alignment on reserved function pointers

---

lib/Target/JSBackend/JSBackend.cpp

This would produce code that was parsed as a prefix decrement operator. A space between both minus signs is enough for it to be interpreted correctly.
There test case for this is here: https://github.com/kripken/emscripten/pull/6228

Fix case where a unary operator is applied to a negative floating point literal.

---

lib/Target/JSBackend/JSBackend.cpp

JS VMs do a lot better on that these days anyhow, and even more so in wasm.

stop warning about very large numbers of local variables

---

lib/Target/JSBackend/JSBackend.cpp

This makes sure that in that mode we have a function pointer for each export, and adds some extra metadata to describe it. It will be useful in https://github.com/kripken/emscripten/issues/6309 where we are trying to get emulation fully working with wasm.

Export function pointers for wasm shared modules with emulated function pointers

---

lib/Target/JSBackend/Relooper.cpp
lib/Target/JSBackend/Relooper.h
tools/opt/CMakeLists.txt

With __declspec(dllexport), only the relooper APIs will be exported in the final DLL when building with MinGW. As a result, the shared build(-DBUILD_SHARED_LIBS=ON) breaks because LLVMJSBackendCodeGen.dll is not exporting all necessary symbols. The patch simply removes this
attribute. MSVC static build is supposed to be unaffected because the relooper APIs now go in LLVMJSBackendCodeGen.lib the same way as other LLVM symbols, and MSVC shared build is just not supported by LLVM.

retire RELOOPERDLL_API to fix MinGW shared build

---

lib/Target/JSBackend/JSBackend.cpp
test/CodeGen/JS/simd-shift.ll

Remove generation of old SIMD.js shiftRightLogicalByScalar and shiftRightArithmeticByScalar, instead those were replaced by shiftRightByScalar, with the SIMD type Int32x4 vs Uint32x4 denoting whether the shift will be sign-extending or not.

fix_simd_right_shift

---

lib/Target/JSBackend/JSBackend.cpp

Fix FRem handling for single precision floats so that it validates as asm.js.
For code
```c
float x = ...;
fmodf(x, 3.14f);
```
fastcomp is now generating
```
$3 = Math_fround($2 % Math_fround(3.1400001));
```
yielding
```
TypeError: asm.js type error: modulo cannot receive float arguments
```
This changes the code to emit
```
$3 = Math_fround(+($2) % +(Math_fround(3.1400001)));
```
so that it validates properly.
Unity is currently hitting this in asm.js builds, in really old code that has not changed in years. I don't know why this all of a sudden misvalidates - perhaps LLVM update changes `fmodf` to no longer go to a function call to musl? Or Firefox behavior change? (Firefox 61.0.1 (64-bit) on Windows gives the error)

fix_frem_for_precise_f32

---

lib/Target/JSBackend/JSBackend.cpp

We did not handle this properly before, without this option, we looked at the similarly-named function pointer emulation flag.
Matched with https://github.com/kripken/emscripten/pull/7318

Receive EMULATED_FUNCTION_POINTER_CASTS

---

lib/Target/JSBackend/JSBackend.cpp

Leave that to the emcc driver to decide. See https://github.com/kripken/emscripten/pull/7319

don't export all functions in relocatable modules in fastcomp

---

lib/Target/JSBackend/CallHandlers.h
lib/Target/JSBackend/JSBackend.cpp

Output used invoke functions from fastcomp so that only the invoke_() functions that are needed can be generated.
It looks like `emscript_wasm_backend` function already referred to a `invoke_funcs = metadata.get('invokeFuncs', [])` field, with this contents, so adding the same to fastcomp side as well.

output_used_invoke_functions

---

lib/Target/JSBackend/JSBackend.cpp

If we are done linking, then they should be resolved to null. (Before this PR, they'd get a function index assigned, so they were non-null, and comparisons to null were incorrect.)

Handle extern_weak functions

---

lib/Target/JSBackend/CallHandlers.h

(unlikely as taking their address might seem)

Callhanders can be called with NULL, to just detect dependencies - atomics too

---

lib/Target/JSBackend/JSBackend.cpp
test/CodeGen/JS/with-overflow.ll

Make sure ExpandArithWithOverflow runs before ExpandStructRegs. While the latter has a check to avoid processing struct returns of intrinsics, it only works when directly extracting from one. In https://github.com/rust-lang/rust/pull/58623 we ran into a case where an extractvalue of an insertvalue of a with.overflow intrinsic is performed, as shown in the test case.

Perform with.overflow expansion before struct reg expansion

---

lib/Target/JSBackend/JSBackend.cpp

This means that the dynamic linker then assigned function pointers
and both main module and side module use `fp$foo` accessors to lookup
function addresses, just like they do for global addresses.
This allows the test_dylink_function_pointer_equality test in emscripten
to pass.
See https://github.com/emscripten-core/emscripten/issues/8268.

When building relocatable code lookup function addresses dynamically via `fp$foo` functions

---

include/llvm/Support/Compiler.h
include/llvm/Support/ManagedStatic.h
lib/Support/CommandLine.cpp

This allows LLVM to be built with clang-cl on windows.
commit 41fe3a54c2613d81a68eb02ae76b394d0b8849ab
Author: Reid Kleckner <rnk@google.com>
Date:   Thu Apr 4 11:30:07 2019
Ensure that ManagedStatic is constant initialized in MSVC 2017 & 2019
Fixes PR41367.
This effectively relands r357655 with a workaround for MSVC 2017.
I tried various approaches with unions, but I ended up going with this
ifdef approach because it lets us write the proper C++11 code that we
want to write, with a separate workaround that we can delete when we
drop MSVC 2017 support.
This also adds LLVM_REQUIRE_CONSTANT_INITIALIZATION, which wraps
[[clang::require_constant_initialization]]. This actually detected a
minor issue when using clang-cl where clang wasn't able to use the
constexpr constructor in MSVC's STL, so …

Cherry-pick upstream r357714

---

include/llvm/Support/ManagedStatic.h
lib/Support/CommandLine.cpp

It's a fix to the previously cherry-picked patch.
commit 4312fee0a9fb5b2bfe4a52766a4abdd35f23c018
Author: Reid Kleckner <rnk@google.com>
Date:   Thu Apr 4 11:45:05 2019
Appease STLs where std::atomic<void*> lacks a constexpr default ctor
MSVC 2019 casts the pointer to a pointer-sized integer, which is a
reinterpret_cast, which is invalid in a constexpr context, so I have to
remove the LLVM_REQUIRES_CONSTANT_INITIALIZATION annotation for now.
llvm-svn: 357716

Cherry-pick upstream r357726

---

lib/Target/JSBackend/JSBackend.cpp

This allows emscripten to avoid reporting errors when these are missing at link time.

Export the names of externals that are declared as weak

---

lib/Target/JSBackend/JSBackend.cpp

This allows native code to export the address of globals using
the normal EMSCRIPTEN_KEEPALIVE mechanism.

Export named globals even in non-relocatable code
